# Generated by Django 3.1.5 on 2022-07-02 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20220702_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('date_birth', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
