# Generated by Django 3.1.5 on 2022-07-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_role_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
