# Generated by Django 3.1.5 on 2022-07-02 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20220702_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('series', models.CharField(max_length=255, verbose_name='Серийный номер устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование системы')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование системы')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Type_devices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа устройства')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Installed_devices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('value', models.CharField(max_length=255, verbose_name='Значение устройства')),
                ('limit_max', models.CharField(max_length=255, verbose_name='Максимальное значение устройства ')),
                ('limit_min', models.CharField(max_length=255, verbose_name='Минимальное значение устройства')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.devices', verbose_name='Устройство')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipment', verbose_name='Оборудование')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.room', verbose_name='Помещение')),
                ('systems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.systems', verbose_name='Система')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Установленное устройство',
                'verbose_name_plural': 'Установленные устройства',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата и время момента фиксации показания')),
                ('status', models.CharField(max_length=3, verbose_name='Состояние устройства (On/Off)')),
                ('meaning', models.PositiveIntegerField(blank=True, null=True)),
                ('installed_devices_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.installed_devices', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата и время возникновения ошибки')),
                ('description', models.CharField(max_length=255, verbose_name='Описание ошибки')),
                ('installed_devices_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.installed_devices', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.manufacturers', verbose_name='Производитель оборудования'),
        ),
        migrations.AddField(
            model_name='devices',
            name='type_devices_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.type_devices', verbose_name='Тип устройства '),
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата заключения договора')),
                ('name', models.CharField(max_length=255, verbose_name='Название промышленного предприятия')),
                ('key_product', models.CharField(max_length=255, verbose_name='Регистрационный ключ продукта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес промышленного предприятия')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
