# Generated by Django 3.1.5 on 2022-07-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20220702_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель оборудования', 'verbose_name_plural': 'Производители оборудования'},
        ),
    ]
