# Generated by Django 3.1.5 on 2022-07-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_system_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='Иконка'),
        ),
    ]
